# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f07e7bd63ac1fba1b762846e319ddd96c97649269300f143c19758ddca35c22e3bc279d015fc8ed6e78675093020b0aed2f9c8eb3d01c0a2bb537e65e5136779

test:
  secret_key_base: 50d617390a0e40f9c4559040c5eb9b11ddc0e56128cf3d9f688d573877391c5fad9e94a4141ad09771bebbe4eadc138fffbfc16352951e0e3ffe6f0971743b28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
